name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.1.0
        with:
          distribution: temurin
          java-version: 11
          cache: "gradle"
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Nemesis"
          path: ./build/libs/ItemMergeFix-*.jar
      - name: Release
        if: github.ref_name == 'main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.0"
          prerelease: false
          title: "Nemesis"
          files: ./build/libs/ItemMergeFix-*.jar